### ISSUE TITLE
Not Able to Create an Alias

### ISSUE THREAD

**Issue by joshuabremerdexcom** [barthr/redo#1]
I tried setting this up and I'm running into trouble.

After setting `$REDO_HISTORY_PATH` explicitly I was able to get redo, but then it fails at the end.

![image](https://user-images.githubusercontent.com/59564543/161297038-2f2f81a7-0e6e-4022-8ee1-8a3466716d67.png)

![image](https://user-images.githubusercontent.com/59564543/161297087-e1916214-deb3-4d61-b363-f27508a36e5b.png)

![image](https://user-images.githubusercontent.com/59564543/161297094-e7ae9e4b-1b8b-4614-978f-6fe8709d15df.png)

Note, I'm running Zshell, and on-my-zsh...but i'm kind of unsure what could be happening here. Any ideas?

**Comment by barthr** [comment]
Did you select a command by using space?

**Comment by joshuabremerdexcom** [comment]
Just tried again. I definitely hit "return".

**Comment by joshuabremerdexcom** [comment]
Ohhh....yes. I didn't select one.

**Comment by joshuabremerdexcom** [comment]
could i offer that as a UX suggestion? if someone hits enter with none selected it goes back to that page? or maybe explains to them that they HAVE to select one with the space bar?

**Comment by barthr** [comment]
Nice suggestion, I will implement that! :+1: 

Currently it shows in the bottom that space is a shortcut for selecting an item which isn't descriptive enough

**Comment by barthr** [comment]
In the new release it is not possible to continue whenever none are selected!
