### ISSUE TITLE
REDO_CONFIG_PATH redundant if REDO_ALIAS_PATH set

### ISSUE THREAD

**Issue by kzshantonu** [barthr/redo#11]
If an alias file is set, the program just creates an empty directory at REDO_CONFIG_PATH. Maybe I care a bit too much about the organization of my `.config` dir

**Comment by barthr** [comment]
That shouldn't be the case. I will fix this in the next release

**Comment by barthr** [comment]
I'm closing this since the redo directory can be used in the future for other configurations, so it is nice to already have it in place.
