### ISSUE TITLE
alias names with spaces will not create an alias

### ISSUE THREAD

**Issue by chris-aeviator** [barthr/redo#5]
When adding an alias for the first time, I'm unaware thath the name is supposed the be alias that I will run later in the terminal. I expected redo to show me a list of names when executing it. While I can understand that redo will create a terminal alias and that's totally fine, it was not obvious what happened after I entered "SSH into tofuland" as the alias name. No error is thrown but also no alias is created.

A warning should be shown if a user iput lead to no new alias creation.

**Comment by barthr** [comment]
Hi @chris-aeviator, thanks for reporting this issue. Indeed the name of the function has to be a valid one according to bash, I will improve the validation in the confirm screen for creating the actual alias!

**Comment by barthr** [comment]
Hi @chris-aeviator, this issue has been resolved. The new release (https://github.com/barthr/redo/releases/tag/v0.5.0) fixes some issues regarding error handling, it is now not possible to create an alias if it is incorrect (you will be prompted to pick another name). Hope this helps!
