### ISSUE TITLE
Visual glitching in command history list

### ISSUE THREAD

**Issue by julesdeckers** [barthr/redo#8]
On __arm64-darwin__ built form source, I experience a visual bug in the ordered command list:
<img width="545" alt="Screenshot 2022-04-21 at 10 26 25" src="https://user-images.githubusercontent.com/44838517/164414208-37f04f7f-13d5-4bbd-ac45-797bfb00e17d.png">
<img width="556" alt="Screenshot 2022-04-21 at 10 26 40" src="https://user-images.githubusercontent.com/44838517/164414261-469c3c90-cfda-4cb5-ac38-98089de642c3.png">

Some of the commands will jump around and dissapear when navigating. Application functions work normally.

## .zshrc variables
<img width="292" alt="Screenshot 2022-04-21 at 10 27 47" src="https://user-images.githubusercontent.com/44838517/164415115-00733648-1f7d-4371-a2ed-e83bffb3052a.png">

Possibly a wrong configuration on my part?

**Comment by barthr** [comment]
Hi @julesdeckers. Thanks for reporting this and using Redo! I myself don't own an arm based darwin machine, however I might have some clues on why this is happening. Are you using your terminal in windowed mode ? especially smaller than what redo needs in terms of terminal drawing space. There are some visual issues whenever this is the case, the UI at this moment does not do proper scaling relative to the terminal window. If this is not the case I will look at a way to test with an arm based machine, however that may take a little more time and doesn't solve your problem per se.
